version: "3"

services:
  server:
    build: .
    restart: always
    environment:
      - REDIS_CONNSTRING=redis://redis
      - ADMIN_SECRET=
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
